name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: buildApi
    steps:
    - task: Cake@2
      inputs:
        script: 'build.cake'
        target: 'PublishAll'
        verbosity: 'Verbose'
    - publish: deploy/api
      artifact: api-build
    - publish: deploy/admin
      artifact: admin-build

- stage: dockerImage
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: dockerBuild
    strategy:
      matrix:
        api:
          imageName: rtuitlab/landing-api
          artifactName: api-build
        admin:
          imageName: rtuitlab/landing-admin
          artifactName: admin-build
    steps:
    - download: current
      artifact: $(artifacrName)
      displayName: Download $(artifacrName)
    - task: Docker@2
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: $(imageName)
        command: 'buildAndPush'
        Dockerfile: '$(Pipeline.Workspace)/$(artifacrName)/Dockerfile'
        buildContext: '$(Pipeline.Workspace)/$(artifacrName)'
        tags: |
          $(Build.BuildId)
          latest
- stage: UpdateService
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/landing-api:$(Build.BuildId) landing_api'
                readyTimeout: '20000'