name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: buildApi
    steps:
    - task: Cake@2
      inputs:
        script: 'build.cake'
        target: 'PublishApi'
        verbosity: 'Verbose'
    - publish: deploy
      artifact: api-build

- stage: dockerImage
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: dockerBuild
    steps:
    - download: current
      artifact: api-build
      displayName: Download api-build
    - task: Docker@2
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/landing-api'
        command: 'buildAndPush'
        Dockerfile: '$(Pipeline.Workspace)/api-build/Dockerfile'
        buildContext: '$(Pipeline.Workspace)/api-build'
        tags: |
          $(Build.BuildId)
          latest