trigger:
- master
- develop

name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: Publish api
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'Landing.API/Landing.API.csproj'
        arguments: '-c Release -o $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false
        modifyOutputPath: false

    - task: PublishBuildArtifacts@1
      displayName: publish landing-api-build
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'landing-api-build'
        publishLocation: 'Container'