version: '3.8'

services:
  api:
    environment:
      GitHubOptinos__OAuthToken: ${GITHUB_OAUTH_TOKEN?Place GITHUB_OAUTH_TOKEN for production}
      ScrubOptions__Delay: 00:30:00
      ConnectionStrings__POSTGRES: ${POSTGRES_DATABASE_CONNECTION_STRING?Place connection string to database POSTGRES_DATABASE_CONNECTION_STRING}
      LandingOptions__AdminPanelAccessToken: ${ADMIN_API_SECRET_TOKEN?Place secret token ADMIN_API_SECRET_TOKEN}
    deploy:
      resources:
          limits:
              cpus: '0.30'
              memory: 100M
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
  admin:
    environment:
      ConnectionStrings__POSTGRES: ${POSTGRES_DATABASE_CONNECTION_STRING?Place connection string to database POSTGRES_DATABASE_CONNECTION_STRING}
      LandingOptions__AdminPanelAccessToken: ${ADMIN_API_SECRET_TOKEN?Place secret token ADMIN_API_SECRET_TOKEN}
      LandingOptions__ApiBaseAddress: ${ADMIN_API_BASE_ADDRESS?Place API base address ADMIN_API_BASE_ADDRESS}
    deploy:
      resources:
          limits:
              cpus: '0.30'
              memory: 100M
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
  preview:
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"