version: '3.8'

services:
    api:
      build: ${BACK_CONTEXT:-.}/deploy/api
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__POSTGRES=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-db;Integrated Security=true;
        - ScrubOptions__Delay=10:00:00
      ports:
        - 5001:5001
    admin:
      build: ${BACK_CONTEXT:-.}/deploy/admin
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__POSTGRES=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-db;Integrated Security=true;
      ports:
        - 5003:5003
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
    preview:
      build: ${BACK_CONTEXT:-.}/deploy/preview
      ports:
        - 5004:5004