version: '3.8'

services:
    api:
      image: rtuitlab/landing-api
    admin:
      image: rtuitlab/landing-admin
      environment:
        LandingOptions__ApiBaseAddress: 'http://api:5001'
    preview:
      image: rtuitlab/landing-preview
