version: '3.8'

services:
    api:
      build: ${BACK_CONTEXT:-.}/deploy/api
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__POSTGRES=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=itlab-db;Integrated Security=true;
      ports:
        - 5001:5001
    admin:
      build: ${BACK_CONTEXT:-.}/deploy/admin
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - 5002:5002
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 300M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
