version: '3.8'

services:
    api:
      image: rtuitlab/landing-api
      deploy:
        resources:
            limits:
                cpus: '0.30'
                memory: 100M
      logging:
          driver: "json-file"
          options:
              max-size: "200k"
              max-file: "10"